---
apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: kafka-consumer  
  namespace: px-delivery         
spec:
  replicas: 1                    
  selector:
    matchLabels:
      app: kafka_consumer
  template:                      
    metadata:
      labels:                    
        app: kafka_consumer
    spec:                        
      containers:
      - name: consumer
        image: eshanks16/kafka_consumer:v1
        env:
          - name: KAFKA_HOST
            value: kf-kafka-nh8epu-px-delivery-0-vip
          - name: KAFKA_USER
            value: pds
          - name: KAFKA_PASS
            value: "44wNYrLa3q8UBKVrw8Jdfoh9JmPB3fX5HRO7I0OU"
          - name: KAFKA_PORT
            value: "9092"
          - name: MYSQL_HOST
            value: "my-mysql2-qllacl-px-delivery-0-vip"
          - name: MYSQL_INIT_USER
            value: "pds"
          - name: MYSQL_INIT_PASS
            value: "3UiaSl18VyuBS9t1doK5kTbA50Z9jRvvrgs6YRyB"
          - name: MYSQL_USER
            value: "porxie"
          - name: MYSQL_PASS
            value: "porxie"
          - name: MYSQL_PORT
            value: "6446"
        imagePullPolicy: Always 
