---
apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: kafka-consumer  
  namespace: px-delivery         
spec:
  replicas: 1                    
  selector:
    matchLabels:
      app: kafka_consumer
  template:                      
    metadata:
      labels:                    
        app: kafka_consumer
    spec:                        
      containers:
      - name: consumer
        image: eshanks16/kafka_consumer:v1
        env:
          - name: KAFKA_HOST
            value: "kf-kafka-y01har-px-delivery-0-vip"
          - name: KAFKA_USER
            value: pds
          - name: KAFKA_PASS
            value: "Ix9Nlx008ss0WwCHmda74cmoBssQ3sbjq1mKn4to"
          - name: KAFKA_PORT
            value: "9092"
          - name: MYSQL_HOST
            value: "my-mysql-77vn9m-px-delivery-0-vip"
          - name: MYSQL_INIT_USER
            value: "pds"
          - name: MYSQL_INIT_PASS
            value: "nS2favlCUT2J02PIEatQ3fPiO3mIy41gaE9zap4j"
          - name: MYSQL_USER
            value: "porxie"
          - name: MYSQL_PASS
            value: "porxie"
          - name: MYSQL_PORT
            value: "6446"
        imagePullPolicy: Always 
