---
apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: pxdelivery  
  namespace: px-delivery         
spec:
  replicas: 1                    
  selector:
    matchLabels:
      app: pxdelivery-web
  template:                      
    metadata:
      labels:                    
        app: pxdelivery-web
    spec:                        
      containers:
      - name: pxdelivery-web
        image: eshanks16/pxdelivery:v1
        env:
        - name: MONGO_INIT_USER
          value: ""
        - name: MONGO_INIT_PASS
          value: ""
        - name: MONGO_HOST
          value: "mongo"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_TLS
          value: "" # Should be empty set unless using AWS DocumentDB
        - name: KAFKA_HOST
          value: "my-release-kafka-headless"
        - name: KAFKA_USER
          value: pds
        - name: KAFKA_PASS
          value: "crQ6dWd8jn6KZL66YB4srovCKsYI5opqXWyUp919"
        - name: KAFKA_PORT
          value: "9092"
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASS
          value: "porxie"
        - name: MYSQL_PORT
          value: "3306"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080  
        livenessProbe:           
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:   
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1    
---
apiVersion: v1
kind: Service
metadata:
  name: pxdelivery-svc
  namespace: px-delivery
  labels:
    app: pxdelivery-web
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: pxdelivery-web
